package org.spongycastle.asn1.x9;

import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier A0;
    public static final ASN1ObjectIdentifier B0;
    public static final ASN1ObjectIdentifier C0;
    public static final ASN1ObjectIdentifier D0;
    public static final ASN1ObjectIdentifier E0;
    public static final ASN1ObjectIdentifier F0;
    public static final ASN1ObjectIdentifier G0;
    public static final ASN1ObjectIdentifier H0;
    public static final ASN1ObjectIdentifier I0;
    public static final ASN1ObjectIdentifier J0;
    public static final ASN1ObjectIdentifier K0;
    public static final ASN1ObjectIdentifier L0;
    public static final ASN1ObjectIdentifier M0;
    public static final ASN1ObjectIdentifier N0;
    public static final ASN1ObjectIdentifier O0;
    public static final ASN1ObjectIdentifier P0;
    public static final ASN1ObjectIdentifier Q0;
    public static final ASN1ObjectIdentifier R0;
    public static final ASN1ObjectIdentifier S0;
    public static final ASN1ObjectIdentifier T0 = new ASN1ObjectIdentifier("1.2.840.10040.4.1");
    public static final ASN1ObjectIdentifier U0 = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
    public static final ASN1ObjectIdentifier V0;
    public static final ASN1ObjectIdentifier W0;
    public static final ASN1ObjectIdentifier X0;
    public static final ASN1ObjectIdentifier Y0;
    public static final ASN1ObjectIdentifier l0;
    public static final ASN1ObjectIdentifier m0;
    public static final ASN1ObjectIdentifier n0;
    public static final ASN1ObjectIdentifier o0;
    public static final ASN1ObjectIdentifier p0;
    public static final ASN1ObjectIdentifier q0;
    public static final ASN1ObjectIdentifier r0;
    public static final ASN1ObjectIdentifier s0;
    public static final ASN1ObjectIdentifier t0;
    public static final ASN1ObjectIdentifier u0;
    public static final ASN1ObjectIdentifier v0;
    public static final ASN1ObjectIdentifier w0;
    public static final ASN1ObjectIdentifier x0;
    public static final ASN1ObjectIdentifier y0;
    public static final ASN1ObjectIdentifier z0;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier);
        l0 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier2);
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier2);
        m0 = aSN1ObjectIdentifier3;
        aSN1ObjectIdentifier3.q("3.1");
        n0 = new ASN1ObjectIdentifier("3.2", aSN1ObjectIdentifier3);
        o0 = new ASN1ObjectIdentifier("3.3", aSN1ObjectIdentifier3);
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier);
        p0 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier4);
        q0 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier));
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier4);
        r0 = aSN1ObjectIdentifier5;
        s0 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier5);
        t0 = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier5);
        u0 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier5);
        v0 = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier5);
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier);
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("0", aSN1ObjectIdentifier6);
        w0 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier7);
        x0 = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier7);
        y0 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier7);
        z0 = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier7);
        A0 = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier7);
        B0 = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier7);
        C0 = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier7);
        aSN1ObjectIdentifier7.q("8");
        aSN1ObjectIdentifier7.q("9");
        D0 = new ASN1ObjectIdentifier("10", aSN1ObjectIdentifier7);
        E0 = new ASN1ObjectIdentifier("11", aSN1ObjectIdentifier7);
        F0 = new ASN1ObjectIdentifier("12", aSN1ObjectIdentifier7);
        G0 = new ASN1ObjectIdentifier("13", aSN1ObjectIdentifier7);
        aSN1ObjectIdentifier7.q("14");
        aSN1ObjectIdentifier7.q("15");
        H0 = new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier7);
        I0 = new ASN1ObjectIdentifier("17", aSN1ObjectIdentifier7);
        J0 = new ASN1ObjectIdentifier("18", aSN1ObjectIdentifier7);
        K0 = new ASN1ObjectIdentifier("19", aSN1ObjectIdentifier7);
        L0 = new ASN1ObjectIdentifier("20", aSN1ObjectIdentifier7);
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier6);
        M0 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier8);
        N0 = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier8);
        O0 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier8);
        P0 = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier8);
        Q0 = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier8);
        R0 = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier8);
        S0 = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier8);
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        V0 = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier9);
        W0 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier9);
        X0 = new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier9);
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.10046");
        Y0 = new ASN1ObjectIdentifier("2.1", aSN1ObjectIdentifier10);
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier10);
        aSN1ObjectIdentifier11.q(C0515Ga.AVLBLTY_ONLY);
        aSN1ObjectIdentifier11.q(C0515Ga.FARE_ONLY);
        aSN1ObjectIdentifier11.q(C0515Ga.FARE_AVLBLTY);
        C1058d.J(aSN1ObjectIdentifier11, "4", "5", "6", "7");
        aSN1ObjectIdentifier11.q("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifier12 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, new ASN1ObjectIdentifier("1.3.133.16.840.9.44"));
        aSN1ObjectIdentifier12.q(C0515Ga.AVLBLTY_ONLY);
        aSN1ObjectIdentifier12.q(C0515Ga.FARE_ONLY);
    }
}
