package org.spongycastle.asn1.sec;

import org.spongycastle.asn1.ASN1ObjectIdentifier;
import org.spongycastle.asn1.x9.X9ObjectIdentifiers;

public interface SECObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F = X9ObjectIdentifiers.M0;
    public static final ASN1ObjectIdentifier G = X9ObjectIdentifiers.S0;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.132.0");
        a = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier);
        b = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier);
        c = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier);
        d = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier);
        e = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier);
        f = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier);
        g = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier);
        h = new ASN1ObjectIdentifier("8", aSN1ObjectIdentifier);
        i = new ASN1ObjectIdentifier("9", aSN1ObjectIdentifier);
        j = new ASN1ObjectIdentifier("10", aSN1ObjectIdentifier);
        k = new ASN1ObjectIdentifier("15", aSN1ObjectIdentifier);
        l = new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier);
        m = new ASN1ObjectIdentifier("17", aSN1ObjectIdentifier);
        n = new ASN1ObjectIdentifier("22", aSN1ObjectIdentifier);
        o = new ASN1ObjectIdentifier("23", aSN1ObjectIdentifier);
        p = new ASN1ObjectIdentifier("24", aSN1ObjectIdentifier);
        q = new ASN1ObjectIdentifier("25", aSN1ObjectIdentifier);
        r = new ASN1ObjectIdentifier("26", aSN1ObjectIdentifier);
        s = new ASN1ObjectIdentifier("27", aSN1ObjectIdentifier);
        t = new ASN1ObjectIdentifier("28", aSN1ObjectIdentifier);
        u = new ASN1ObjectIdentifier("29", aSN1ObjectIdentifier);
        v = new ASN1ObjectIdentifier("30", aSN1ObjectIdentifier);
        w = new ASN1ObjectIdentifier("31", aSN1ObjectIdentifier);
        x = new ASN1ObjectIdentifier("32", aSN1ObjectIdentifier);
        y = new ASN1ObjectIdentifier("33", aSN1ObjectIdentifier);
        z = new ASN1ObjectIdentifier("34", aSN1ObjectIdentifier);
        A = new ASN1ObjectIdentifier("35", aSN1ObjectIdentifier);
        B = new ASN1ObjectIdentifier("36", aSN1ObjectIdentifier);
        C = new ASN1ObjectIdentifier("37", aSN1ObjectIdentifier);
        D = new ASN1ObjectIdentifier("38", aSN1ObjectIdentifier);
        E = new ASN1ObjectIdentifier("39", aSN1ObjectIdentifier);
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.132.1");
        H = new ASN1ObjectIdentifier("11.0", aSN1ObjectIdentifier2);
        I = new ASN1ObjectIdentifier("11.1", aSN1ObjectIdentifier2);
        J = new ASN1ObjectIdentifier("11.2", aSN1ObjectIdentifier2);
        K = new ASN1ObjectIdentifier("11.3", aSN1ObjectIdentifier2);
        L = new ASN1ObjectIdentifier("14.0", aSN1ObjectIdentifier2);
        M = new ASN1ObjectIdentifier("14.1", aSN1ObjectIdentifier2);
        N = new ASN1ObjectIdentifier("14.2", aSN1ObjectIdentifier2);
        O = new ASN1ObjectIdentifier("14.3", aSN1ObjectIdentifier2);
        P = new ASN1ObjectIdentifier("15.0", aSN1ObjectIdentifier2);
        Q = new ASN1ObjectIdentifier("15.1", aSN1ObjectIdentifier2);
        R = new ASN1ObjectIdentifier("15.2", aSN1ObjectIdentifier2);
        S = new ASN1ObjectIdentifier("15.3", aSN1ObjectIdentifier2);
        C1058d.J(aSN1ObjectIdentifier2, "16.0", "16.1", "16.2", "16.3");
    }
}
