package org.spongycastle.asn1.pkcs;

import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").v();
    public static final ASN1ObjectIdentifier K = lf.p("1.2.840.113549.1.7.2");
    public static final ASN1ObjectIdentifier L = new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").v();
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier a0;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier b0;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier c0 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier d0 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier e0 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.5");
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier f0 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.10");
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, new ASN1ObjectIdentifier("1.2.840.113549.1.3"));
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        a = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier);
        b = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier);
        c = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier);
        d = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier);
        e = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier);
        aSN1ObjectIdentifier.q("6");
        f = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier);
        g = new ASN1ObjectIdentifier("8", aSN1ObjectIdentifier);
        h = new ASN1ObjectIdentifier("9", aSN1ObjectIdentifier);
        i = new ASN1ObjectIdentifier("10", aSN1ObjectIdentifier);
        j = new ASN1ObjectIdentifier("11", aSN1ObjectIdentifier);
        k = new ASN1ObjectIdentifier("12", aSN1ObjectIdentifier);
        l = new ASN1ObjectIdentifier("13", aSN1ObjectIdentifier);
        m = new ASN1ObjectIdentifier("14", aSN1ObjectIdentifier);
        n = new ASN1ObjectIdentifier("15", aSN1ObjectIdentifier);
        String str = "15";
        o = new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier);
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        q = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier2);
        r = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier2);
        s = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier2);
        t = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier2);
        u = new ASN1ObjectIdentifier("10", aSN1ObjectIdentifier2);
        v = new ASN1ObjectIdentifier("11", aSN1ObjectIdentifier2);
        w = new ASN1ObjectIdentifier("13", aSN1ObjectIdentifier2);
        x = new ASN1ObjectIdentifier("12", aSN1ObjectIdentifier2);
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        y = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier3);
        z = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier3);
        A = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier3);
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        B = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier4);
        C = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier4);
        D = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier4);
        E = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier4).v();
        F = new ASN1ObjectIdentifier("8", aSN1ObjectIdentifier4).v();
        G = new ASN1ObjectIdentifier("9", aSN1ObjectIdentifier4).v();
        H = new ASN1ObjectIdentifier("10", aSN1ObjectIdentifier4).v();
        I = new ASN1ObjectIdentifier("11", aSN1ObjectIdentifier4).v();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7").v();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").v();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").v();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").v();
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        M = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier5).v();
        N = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier5).v();
        O = new ASN1ObjectIdentifier("8", aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier("9", aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier("13", aSN1ObjectIdentifier5).v();
        String str2 = "14";
        new ASN1ObjectIdentifier(str2, aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier(str, aSN1ObjectIdentifier5).v();
        ASN1ObjectIdentifier v2 = new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier5).v();
        P = new ASN1ObjectIdentifier("20", aSN1ObjectIdentifier5).v();
        Q = new ASN1ObjectIdentifier("21", aSN1ObjectIdentifier5).v();
        aSN1ObjectIdentifier5.q("22.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("22", aSN1ObjectIdentifier5);
        R = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier6).v();
        new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier6).v();
        new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, new ASN1ObjectIdentifier("23", aSN1ObjectIdentifier5)).v();
        new ASN1ObjectIdentifier("52", aSN1ObjectIdentifier5).v();
        new ASN1ObjectIdentifier("15.1", aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier("15.2", aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier("15.3", aSN1ObjectIdentifier5);
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        aSN1ObjectIdentifier7.q(C0515Ga.FARE_ONLY);
        aSN1ObjectIdentifier7.q("4");
        aSN1ObjectIdentifier7.q("9");
        aSN1ObjectIdentifier7.q("23");
        aSN1ObjectIdentifier7.q("31");
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, v2);
        aSN1ObjectIdentifier8.q("9");
        aSN1ObjectIdentifier8.q(str2);
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        C1058d.J(aSN1ObjectIdentifier9, C0515Ga.AVLBLTY_ONLY, C0515Ga.FARE_ONLY, C0515Ga.FARE_AVLBLTY, "4");
        aSN1ObjectIdentifier9.q("5");
        aSN1ObjectIdentifier9.q("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        aSN1ObjectIdentifier10.q(C0515Ga.AVLBLTY_ONLY);
        C1058d.J(aSN1ObjectIdentifier10, "4", "5", "10", "11");
        aSN1ObjectIdentifier10.q("12");
        aSN1ObjectIdentifier10.q("47");
        aSN1ObjectIdentifier10.q("7");
        aSN1ObjectIdentifier10.q(str2);
        new ASN1ObjectIdentifier(str, aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier("17", aSN1ObjectIdentifier10);
        aSN1ObjectIdentifier10.q("18");
        new ASN1ObjectIdentifier("19", aSN1ObjectIdentifier10);
        C1058d.J(aSN1ObjectIdentifier10, "20", "21", "22", "23");
        C1058d.J(aSN1ObjectIdentifier10, "24", "25", "26", "27");
        C1058d.J(aSN1ObjectIdentifier10, "37", "38", "54", "43");
        aSN1ObjectIdentifier10.q("40");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        ASN1ObjectIdentifier aSN1ObjectIdentifier12 = new ASN1ObjectIdentifier("10.1", aSN1ObjectIdentifier11);
        S = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier12);
        T = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier12);
        U = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier12);
        aSN1ObjectIdentifier12.q("4");
        aSN1ObjectIdentifier12.q("5");
        aSN1ObjectIdentifier12.q("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier13 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier11);
        V = aSN1ObjectIdentifier13;
        W = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier13);
        X = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier13);
        Y = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier13);
        Z = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier13);
        a0 = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier13);
        b0 = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier13);
        aSN1ObjectIdentifier13.q("6");
    }
}
