package org.spongycastle.asn1.nist;

import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface NISTObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier a0;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier b0;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier c0;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier d0;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier e0;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("2.16.840.1.101.3.4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier);
        a = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier2);
        b = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier2);
        c = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier2);
        d = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier2);
        e = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier2);
        f = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier2);
        g = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier2);
        h = new ASN1ObjectIdentifier("8", aSN1ObjectIdentifier2);
        i = new ASN1ObjectIdentifier("9", aSN1ObjectIdentifier2);
        j = new ASN1ObjectIdentifier("10", aSN1ObjectIdentifier2);
        k = new ASN1ObjectIdentifier("11", aSN1ObjectIdentifier2);
        l = new ASN1ObjectIdentifier("12", aSN1ObjectIdentifier2);
        m = new ASN1ObjectIdentifier("13", aSN1ObjectIdentifier2);
        n = new ASN1ObjectIdentifier("14", aSN1ObjectIdentifier2);
        o = new ASN1ObjectIdentifier("15", aSN1ObjectIdentifier2);
        p = new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier2);
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier);
        q = aSN1ObjectIdentifier3;
        r = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier3);
        s = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier3);
        t = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier3);
        u = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier3);
        v = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier3);
        w = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier3);
        x = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier3);
        y = new ASN1ObjectIdentifier("8", aSN1ObjectIdentifier3);
        z = new ASN1ObjectIdentifier("21", aSN1ObjectIdentifier3);
        A = new ASN1ObjectIdentifier("22", aSN1ObjectIdentifier3);
        B = new ASN1ObjectIdentifier("23", aSN1ObjectIdentifier3);
        C = new ASN1ObjectIdentifier("24", aSN1ObjectIdentifier3);
        D = new ASN1ObjectIdentifier("25", aSN1ObjectIdentifier3);
        E = new ASN1ObjectIdentifier("26", aSN1ObjectIdentifier3);
        F = new ASN1ObjectIdentifier("27", aSN1ObjectIdentifier3);
        G = new ASN1ObjectIdentifier("28", aSN1ObjectIdentifier3);
        H = new ASN1ObjectIdentifier("41", aSN1ObjectIdentifier3);
        I = new ASN1ObjectIdentifier("42", aSN1ObjectIdentifier3);
        J = new ASN1ObjectIdentifier("43", aSN1ObjectIdentifier3);
        K = new ASN1ObjectIdentifier("44", aSN1ObjectIdentifier3);
        L = new ASN1ObjectIdentifier("45", aSN1ObjectIdentifier3);
        M = new ASN1ObjectIdentifier("46", aSN1ObjectIdentifier3);
        N = new ASN1ObjectIdentifier("47", aSN1ObjectIdentifier3);
        O = new ASN1ObjectIdentifier("48", aSN1ObjectIdentifier3);
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier);
        P = new ASN1ObjectIdentifier(C0515Ga.AVLBLTY_ONLY, aSN1ObjectIdentifier4);
        Q = new ASN1ObjectIdentifier(C0515Ga.FARE_ONLY, aSN1ObjectIdentifier4);
        R = new ASN1ObjectIdentifier(C0515Ga.FARE_AVLBLTY, aSN1ObjectIdentifier4);
        S = new ASN1ObjectIdentifier("4", aSN1ObjectIdentifier4);
        T = new ASN1ObjectIdentifier("5", aSN1ObjectIdentifier4);
        U = new ASN1ObjectIdentifier("6", aSN1ObjectIdentifier4);
        V = new ASN1ObjectIdentifier("7", aSN1ObjectIdentifier4);
        W = new ASN1ObjectIdentifier("8", aSN1ObjectIdentifier4);
        X = new ASN1ObjectIdentifier("9", aSN1ObjectIdentifier4);
        Y = new ASN1ObjectIdentifier("10", aSN1ObjectIdentifier4);
        Z = new ASN1ObjectIdentifier("11", aSN1ObjectIdentifier4);
        a0 = new ASN1ObjectIdentifier("12", aSN1ObjectIdentifier4);
        b0 = new ASN1ObjectIdentifier("13", aSN1ObjectIdentifier4);
        c0 = new ASN1ObjectIdentifier("14", aSN1ObjectIdentifier4);
        d0 = new ASN1ObjectIdentifier("15", aSN1ObjectIdentifier4);
        e0 = new ASN1ObjectIdentifier("16", aSN1ObjectIdentifier4);
    }
}
